=== nithingangula123-blip/Full_Stack_Practice/10.2 Grid Placement/bookstore.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="bookstore">
<xs:complexType>
<xs:sequence>
<xs:element name="student">
<xs:complexType>
<xs:sequence>
<xs:element name="name" type="xs:string"/>
<xs:element name="rollno" type="xs:int"/>
<xs:element name="section" type="xs:string"/>
<xs:element name="branch" type="xs:string"/>
<xs:element name="age" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="books">
<xs:complexType>
<xs:sequence>
<xs:element name="book" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="title" type="xs:string"/>
<xs:element name="author" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element></xs:schema>

=== nithingangula123-blip/Full_Stack_Practice/10.2 Grid Placement/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookstore.xsd">
<student>
<name>Nithin</name>
<rollno>1285</rollno>
<section>B</section>
<branch>Information Technology</branch>
<age>20</age>
</student>
<books>
<book>
<title>Hapiness</title>
<author>Nithin</author>
</book>
<book>
<title>Do every thing</title>
<author>Mani</author>
</book>
<book>
<title>How to earn</title>
<author>Sai</author>
</book>
</books>
</bookstore>
